### ISSUE TITLE
SQL constraints (eg. primary key) checking

### ISSUE THREAD

**Issue by jonashaag** [Quantco/datajudge#21]
Snowflake doesn't support primary keys. (You may define primary keys and it remembers them as metadata but doesn't check them for integrity, eg. uniqueness.)

Would be helpful to be able to check primary keys, and possibly other SQL-native constraints, with the help of datajudge.

We're likely to build this for a project so I wonder what datajudge folks think about the feature.

**Comment by kklein** [comment]
Hi! Just to be clear/make it explicit: Have you looked into `Uniqueness`? At first sight it might do what you are describing.

https://datajudge.readthedocs.io/en/latest/api/datajudge.requirements.html#datajudge.requirements.WithinRequirement.add_uniqueness_constraint

**Comment by jonashaag** [comment]
Nice, yes that could be part of a solution.

I am looking for something that will read constraints from the SQL database's metadata and test those constraints.

**Comment by kklein** [comment]
> I am looking for something that will read constraints from the SQL database's metadata and test those constraints.

Could that something also be a mechanism on the user end, translating database metadata to datajudge `Constraint`s or did you envision this to be part of datajudge?

**Comment by jonashaag** [comment]
If you're talking about code generation, that could be a valid solution (although I'm sceptical it's a good one).

In any case I think it would be valuable to have this as part of datajudge or as a datajudge-sql-constraints package or something, as it's a common requirement for users of data warehouses.

**Comment by YYYasin19** [comment]
To have an update on this topic: 
I have implemented a very short snippet that executes this for a project I work on.
The code is basically more or less just
```py
def get_primary_keys(db_schema: str, table: str) -> list[str]:
    result = pandas.read_sql("SHOW PRIMARY KEYS in {db_schema}.{table}", connection)
    return result["column_name"].values.tolist()
```
and then plain datajudge
```py
def create_pk_enforcing_requirements(db_schema: str) -> List[Requirement]:
    reqs = []
    for table in tables:
        pk_columns = get_primary_keys(db_schema, table)
        req = WithinRequirement.from_table(...)
        req.add_uniqueness_constraint(columns=pk_columns)
        reqs.append(req)
    
    return reqs
```
---
We could of course add this function as some kind of helper constraint, e.g. like the following:
```
# no other information needed
requirement.add_primary_key_constraint()
```
which internally would also just fetch the primary keys and add a uniqueness constraint.
⚠️ But: Retrieving the Primary Keys for a table is non-trivial and requires [seperate implementations for different database flavors](https://stackoverflow.com/questions/12379221/sql-query-to-find-primary-key-of-a-table).

I see the following options:
Solution Nr.1: We still implement it and have a few if-then-else cases :)
Solution Nr.2: We have a short comment in the documentation for other uses that might search for this and how they can achieve it depending on their own database engine.
Solution Nr.3: We acknowledge the issue and decide not to implement it at all for now (also valid)

What do you think?

**Comment by jonashaag** [comment]
I'm very much in favor of having a solution that doesn't require downstream users to write their own constraint-fetching code: I'm pretty sure most downstream implementations will be wrong in one way or another. Better have a correct one here (or in another library)

**Comment by kklein** [comment]
@YYYasin19 Thanks for the careful write-up!

> Retrieving the Primary Keys for a table is non-trivial and requires [seperate implementations for different database flavors](https://stackoverflow.com/questions/12379221/sql-query-to-find-primary-key-of-a-table).

Have you found an edge-case where this isn't working?
https://github.com/Quantco/datajudge/blob/main/src/datajudge/db_access.py#L795-L797

> We could of course add this function as some kind of helper constraint, e.g. like the following:

I like the idea! I could even image merely adding a parameter to `add_uniqueness_constraint` indicating that the primary keys are supposed to be read out from database.

**Comment by YYYasin19** [comment]
> Does SQLAlchemy provide a common API for retrieving PKs?

Yes! 🥳 
Didn't think it would have, but it's there.
The following works:
```py
from sqlalchemy.inspection import inspect
engine = ... # create database engine or connection somehow
inspector = inspect(engine)
inspector.get_pk_constraint(table_name, schema_name)
> {'constrained_columns': [<list of pk columns>], 'name': '<constraint name>'}
```

**Comment by YYYasin19** [comment]
@kklein Sorry, I didn't mean to ignore your comment, it just didn't show in my UI.

At first, trying `TableDataSource(db, "TABLE_NAME", "SCHEMA").get_clause(engine).primary_keys` (which is what `get_primary_keys()` does) showed an empty collection.
It only worked after I used a lowercase table name:
`TableDataSource(db, "table_name", "SCHEMA").get_clause(engine).primary_keys`.
I am using snowflake in production and I know that has been an issue in the past. Is this a know issue?

---
Otherwise, your solution is perfect, sorry for missing the function! 😬 
I'd rather add a new method to not cause any more confusion with the parameters of the `add_uniqueness_constraint`-method.

**Comment by kklein** [comment]
The docs[0] say that when using a snowflake engine, all columns should be lower-cased by datajudge. Yet, this can't be expected to hold when using internal objects such as `TableDataSource` - rather it only holds when using a `Requirement`'s interface.

> Otherwise, your solution is perfect, sorry for missing the function! 

Excellent, glad to hear that!

> I'd rather add a new method to not cause any more confusion with the parameters of the add_uniqueness_constraint-method.

I'd have a strong preference to add id to the existing method via a parameter. My preference is based on two reasons:
* We already have two Constraints/methods having to do with primary keys. It is already somewhat of a burden to the user to understand the different semantics. With three methods this would even be harder.
* Both constraints would share a lot of their logic - merely the source of the columns to compare with would be different. This sounds like DRY to me.

Moreover, I'm not sure what would be confusing about adding, a `infer_columns` - or however it might be called - boolean parameter.

[0] https://datajudge.readthedocs.io/en/latest/getting_started.html#column-capitalization

**Comment by jonashaag** [comment]
Re: adding a parameter, how would this design extend to other constraints that might be in the database? Primary key uniqueness constraints are just a specific case of uniqueness constraints, and that's just a specific case of general constraints.

If we design with separation of concerns in mind, we should end up with something like

- An API to check constraints.
- Another API to retrieve constraint definitions from the database.

This allows for:

- Checking constraints that are defined in the database.
- Checking constraints that are not defined in the database.
- Getting constraints from the database and doing other things with them.

If we mix checking and retrieval we lose flexibility at no advantage that I can see right now.

--

In the docs I've only found this thing that's related to primary keys:

> add_primary_key_definition_constraint
> Primary keys of exactly equal to given column names in the database.

I don't understand what this does though.

**Comment by kklein** [comment]
> Re: adding a parameter, how would this design extend to other constraints that might be in the database? 

I'm not sure which sql constraints you have in mind but a priori create a new datajudge `Constraint` for it and add a corresponding method to a `WithinRequirement` object. Likely similar in nature to the `ColumnType` [0], `NullAbsence` [1] or `PrimaryKeyDefinition` [2] `Constraint`s.

> If we design with separation of concerns in mind, we should end up with something like
> - An API to check constraints.
> - Another API to retrieve constraint definitions from the database.

I'm not sure what exactly you mean by 'API' here. In a way, one might think of `db_access` as an internal API - that is also available to an end user - where almost all of the retrieval takes place. From my perspective it doesn't matter whether the retrieved content would rather be thought of as metadata, e.g. a column type, or data, e.g. a column mean.

As I pointed out before, e.g. the method `get_primary_keys` from `db_access` can be used by an end-user to do just that. 

In order to provide the most convenient user experience, the advertised interface of datajudge, relying on instantiating `Requirement` objects and calling `add_x_constraint` methods on them, does abstracts away this separation - even though it does exist under the hood.

On a far more concrete level, one can currently already do the following (in spirit - I haven't run this code):

```python
import datajudge.db_access as db_access
from datajduge import WithinRequirement

req = WithinRequirement.from_table(
    db_name=my_db,
    schema_name=my_schema,
    table_name=my_table,
)

pk_columns = db_access.get_primary_keys(engine, ref.data_source)
req.add_uniqueness_constraint(columns=pk_columns)

```

Yet, this requires access to an engine at test creation time - in contrast to test execution time.

Hence, I'd find it useful to change the signature of `add_uniqueness_constraint` to not always expect a `columns` parameter but to also be able to call `get_primary_keys` by itself. This could be conveyed in its `retrieve` method[3].

> In the docs I've only found this thing that's related to primary keys:

There is the one you found, `add_primary_key_definition_constraint`, and the one Yasin and I referred to before, `add_uniqueness_constraint`. The former validates whether a primary key constraint formally exists in the database, the latters validates whether the conceptual, necessary predicate of a primary key is satisfied. 

[0] https://github.com/Quantco/datajudge/blob/main/src/datajudge/constraints/column.py#L71
[1] https://github.com/Quantco/datajudge/blob/main/src/datajudge/constraints/miscs.py#L100
[2] https://github.com/Quantco/datajudge/blob/main/src/datajudge/constraints/miscs.py#L10
[3] https://github.com/Quantco/datajudge/blob/main/src/datajudge/constraints/base.py#L171

**Comment by YYYasin19** [comment]
I think my problem with adding a new parameter to the method stems from the pain of using other large libraries and their billions of params and all of them being optional, e.g. just about anything in`pandas` or `sns.barplot`. I would rather have a new method, with a concrete name and sensible defaults where my IDE may even propose the correct method. Instead, I have to read the doc for `add_uniqueness_constraint` and find out that it can be used for PKs.

_BUT_ this is just a minor point and datajudge is nowhere near the "complexity" of the packages I just mentioned. I was just thinking in terms of the future :)

So I am fine with both for now
```py
req.add_primary_key_constraint() # no params
req.add_uniqueness_constraint(columns=None, infer_primary_keys=True)
```

**Comment by kklein** [comment]
@jonashaag @YYYasin19 Can this be closed thanks to https://github.com/Quantco/datajudge/pull/66?
