### ISSUE TITLE
Way to provide custom name for `get_description()`

### ISSUE THREAD

**Issue by jonashaag** [Quantco/datajudge#6]
Currently it's not obvious how to select a single constraint when using `pytest -k`. The pytest test names are taken from `get_description()` which may be something like `...table1|table2`. Problems with that:

- Test names are not necessarily unique and pytest seems to append 0, 1, 2, ... to the names.
- `pytest -k` doesn't allow to specific things like `table1|table2` because of the `|`

Idea: Provide a way to add your own name to each of the requirements/constraints?

**Comment by kklein** [comment]
> better readability, especially with a large test/requirement suite

I'm not exactly sure I understand what you mean. Especially with a very large test suite - with say >1000 tests - how do custom names, help with readability?

> The latter could maybe also be achieved by adding a mark attribute

Exactly! This is done at QuantCo on several projects. This is also elaborated on in this article[0] of our documentation.


> This might be just constraint-specific stuff. Example: For the Uniqueness Constraint, I would love to see in the output which columns were tested.

I would think that this kind of information could be conveyed through the assertion text. In the particular example you give I'm surprised that the columns aren't already part of the assertion text, see this piece of code[1]. If you have found a counterexample/bug, please feel free to open a separate issue!

[0] https://datajudge.readthedocs.io/en/latest/testing.html
[1] https://github.com/Quantco/datajudge/blob/main/src/datajudge/constraints/miscs.py#L92-L95

**Comment by YYYasin19** [comment]
> Especially with a very large test suite - with say >1000 tests - how do custom names, help with readability?

Custom names might help because I might be using the same `constraint` for different cases.
An example: I have 5 dumps with ~30 tables each and there are 10 distinct tests for each table pair from old -> new dump (for the BetweenRequirements)
I might be using `Uniqueness` to validate something and then also validate primary keys for all of my tables as well while I'm there. This will cause my list to have 300 (= 5 * 30 * 2) test entries that all start with `Uniqueness::{dump_name}...`.
If I could have something like a metadata field that is printed along, half of those might be called `UniqueColumn` and the other half maybe `PrimaryKeyValidation` etc.

I think the main points here are:
- I might not know the name of each constraint that I'm testing my data with
- Sometimes, test names are not unique (as mentioned above, they end in `...0` etc.)

> already part of the assertion text

Good point! I think we rather focused on having such information in the test name, but that might be an edge case for datajudge.
