### ISSUE TITLE
Question/Feature Request: Check distribution of unique values in column

### ISSUE THREAD

**Issue by jonashaag** [Quantco/datajudge#87]
Scenario: We have a bunch of tables that each contain the same column C that has unique values in [0, 10]. Each table has a different unique distribution of those values and we want to check that the distributions are as we expect, with some tolerance.

Example:

- Table 1
  - 1: [0.4, 0.5] (at least 40% and at most 50% of values in C are = 1)
- Table 2
  - 1: [0, 0.01] (at most 1% of values in C are = 1)
  - 2: [0.6, 1] (at least 60% of values in C are = 2)
- All tables:
  - 0: [0, 0] (no values are 0)
  - 3-10: [0, 0.05] (at most 5% of values in C are >= 3)

How would you achieve something like this nicely in datajudge?

Thanks a lot!

**Comment by kklein** [comment]
Hi!

Generally speaking, if you'd like to make statements about whether two empirical, categorical distributions are drawn from the same data-generating process, something like a two-sample Chi-squared hypothesis test might be the go to. We don't have such a test implemented in datajudge as of now but would be open to if this would clearly help you.

My current understanding of your use case is that you'd like to do something different anyway - for which existing datajudge functionalities should already help.

> Table 1
1: [0.4, 0.5] (at least 40% and at most 50% of values in C are = 1)

```
req = WithinRequirement.from_table("table1", ...)
req.add_n_rows_min_constraint(
    n_rows_min = .4 * n,
    condition = Condition(raw_string="C = 1")
)
req.add_n_rows_max_constraint(
    n_rows_min = .5 * n,
    condition = Condition(raw_string="C=1")
)
```
where `n`, the total number of rows, would need to be determined ahead of time. If this would be useful to you, we could add a relative reference value to `add_n_rows_max/min_constraint` - instead of only having the current, absolute one. Just lmk.

I think the other examples are analogous.

These examples are all comparing one table at a time against a fixed reference value (say 40% and 50%). One may also want to change this and compare tables against each other. This would work very similarly, using e.g. `add_n_rows_max_gain_constraint` and a `Condition` for both tables.

**Comment by jonashaag** [comment]
Thanks, relative numbers would be a useful addition here! That said, I feel like the interface in this particular case is cumbersome. It's not clear to me in what cases one specifies things in the `**kwargs` of an `add_..._constraint` method and in what cases things must go into `Condition`.

**Comment by jonashaag** [comment]
So far I've solved most of the checks (the lower-bound ones) using

```
add_numeric_between_constraint(col, n, n, lower_bound)
```

but that's also a little cumbersome because it only allows for a lower bound and it requires me to pass `n` twice.

**Comment by kklein** [comment]
> It's not clear to me in what cases one specifies things in the **kwargs of an add_..._constraint method and in what cases things must go into Condition.

The `add_x_constraint` method of a `WithinRequirement` often has three key parameters:
* `column` or `columns`: specifying that the constraint is to be applied to a specific column or collection thereof
* a reference value; in this case `n_rows_min` or `n_rows_max` in a different scenario it could be the desired mean of a numeric column
* a tolerance criterion; in this case nothing in a different scenario it could be the tolerated deviation from a mean.

Importantly, the reference value parameter vanishes when using `BetweenRequirement`s.

Now these parameters rather serve the logical definition of the test - one could say the structure. The `Condition` rather serve to further specify what data is ingested into said test - one could say the content, a subselection of rows to feed into it.

Most importantly I would say that nothing *must* be done in a specific way - whatever works for you. With free text `Condition`s and features such as creating `Requirement`s from free text queries we gave in to users' requests to have more flexibility. This inevitably leads to situations where the same (or a similar) thing can be done in several ways.

> Thanks, relative numbers would be a useful addition here! 

Sure, we can take a stab at that.

> That said, I feel like the interface in this particular case is cumbersome.

If you'd like to further elaborate on what you find cumbersome, I'm all ears.

**Comment by jonashaag** [comment]
One source of confusion/annoyance is that if you go from

```
# Check that C=1 for at least 90% of rows
add_numeric_between_constraint(C, 1, 1, 0.9)
```

a small variant of this

```
# Check that C=1 for at least 90% and at most 95% of rows
add_n_rows_min_constraint(
    n_rows_min_rel=0.9,
    condition = Condition(raw_string="C = 1")
)
add_n_rows_max_constraint(
    n_rows_max_rel=0.95,
    condition = Condition(raw_string="C = 1")
)
```

you'll end up using an entirely different interface.

What adds to the confusion is that in the first example the number of rows is in the *tolerance parameter* whereas in the second one it is in the *reference parameter*, and the vice-versa with the condition `C=1`.

Maybe in this case it is fixed easily by adding a relative upper bound to `add_numeric_between_constraint`.

**Comment by kklein** [comment]
> One source of confusion/annoyance is that if you go from [...] to a small variant of this [...] you'll end up using an entirely different interface.

I'd argue that that's to be expected since these constraints do entirely different things based on different assumptions. One might argue that using a `numeric_between_constraint` in this scenario is a bit of a stretch since one applies it to a categorical, i.e. not a numerical column. 

More generally I would argue that if using functionality in a way it isn't intended - which is totally fine - the usage will indeed look differently from what was intended.

>  in the first example the number of rows is in the tolerance parameter

I figure one might interpret it that way - I wouldn't. I would consider the `min_fraction` parameter as a reference value. My motivation is as follows: If one was to swap this within-test with a between-test, it would vanish: one would say that one expect roughly the same mass (`min_fraction`) to lie between bounds `a` and `b` for both tables. A tolerance parameter, on the other hand, would persist.

**Comment by jonashaag** [comment]
> One might argue that using a `numeric_between_constraint` in this scenario is a bit of a stretch since one applies it to a categorical

Fair point! How does my argument change if it were a numerical column and I'd like to test `2.71 <= C <= 3.14`?

> I would consider the `min_fraction` parameter as a reference value

But then what are `lower_bound` and `upper_bound`? If not reference values, are they conditions? Then why don't they go to the `condition=` part?

**Comment by kklein** [comment]
> Fair point! How does my argument change if it were a numerical column and I'd like to test 2.71 <= C <= 3.14?

There I would say that I'd advise against using `add_n_rows_min` or `n_rows_max` since one would replicate with conjunction and `Condition`s (which one often can, given the power of free text) what `add_numerical_between_constraint` already does for one. 

With categoricals I would _a priori_ advise to use `add_numerical_between_constraint` because it wasn't built for categoricals and could therefore behave or look a little strange.

> But then what are lower_bound and upper_bound? If not reference values, are they conditions? Then why don't they go to the condition= part?

They fulfill the a similar role as the `column` or `columns` parameters and could've totally gone into a `Condition`. Since they will be used every single time this `Constraint` is used, this is meant to be a more convenient option.

**Comment by kklein** [comment]
> If this would be useful to you, we could add a relative reference value to add_n_rows_max/min_constraint - instead of only having the current, absolute one. Just lmk.

On second thought I'm no longer convinced that this would make sense. Rather, I'd suggest the following:

```python
req = BetweenRequirement.from_table("table1", ..., "table1", ...)
req.add_n_rows_min_gain_constraint(
    constant_max_relative_loss = .4,
    condition1 = Condition(raw_string="C = 1"),
    condition2 = None,
)
req.add_n_rows_max_gain_constraint(
    constant_max_relative_loss = .5,
    condition1 = Condition(raw_string="C = 1"),
    condition2 = None,
)
```

Basically, the conditioned table is compared with the non-conditioned table.

**Comment by jonashaag** [comment]
Thanks! I would not be able to come up with this way of thinking about this particular check on my own. I think we will just prefer hand-written SQL in this case:

```py
def test_c1_40_50(engine):
	total_count = engine.execute("select count(*) from T")
	c1_count = engine.execute("select count(*) from T where C=1")
	assert 0.4 <= c1_count / total_count <= 0.5
```

**Comment by jonashaag** [comment]
@kklein @0xbe7a does #145 implement this or is it something different?
